package net.orion.facelinked.profile;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import net.orion.facelinked.config.AutoPrimaryKey;
import net.orion.facelinked.config.PrimaryKey;
import net.orion.facelinked.networks.NetworkMember;
import net.orion.facelinked.networks.NetworkMemberConverter;
import org.springframework.data.annotation.Id;

import java.util.List;

@Data
@DynamoDBTable(tableName = "FaceSmash")
public class FaceSmash {
    @Id
    @DynamoDBAutoGeneratedKey
    Long id;

    @DynamoDBAttribute(attributeName = "user1")
    @DynamoDBTypeConverted(converter = NetworkMemberConverter.class)
    NetworkMember user1;
    @DynamoDBAttribute(attributeName = "user2")
    @DynamoDBTypeConverted(converter = NetworkMemberConverter.class)
    NetworkMember user2;
    @DynamoDBAttribute(attributeName = "likes")
    Integer likes;
    @DynamoDBAttribute(attributeName = "dislikes")
    Integer dislikes;
    @DynamoDBAttribute(attributeName = "likeList")
    List<String> likeList;
    @DynamoDBAttribute(attributeName = "dislikeList")
    List<String> dislikeList;
    @DynamoDBAttribute(attributeName = "week")
    Integer week;

    public FaceSmash() {
    }

    public FaceSmash(NetworkMember user1, NetworkMember user2, int likes, int dislikes, List<String> likeList, List<String> dislikeList, int week) {
        this.user1 = user1;
        this.user2 = user2;
        this.likes = likes;
        this.dislikes = dislikes;
        this.likeList = likeList;
        this.dislikeList = dislikeList;
        this.week = week;
    }
}
