services:
  database:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_PASSWORD=5875662'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
  mongodb:
    image: 'mongo:latest'
    container_name: 'mongo_db'
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=user'
      - 'MONGO_INITDB_ROOT_PASSWORD=5236492'
      - 'MONGO_INITDB_DATABASE=facelinked'
volumes:
    mongo: {}