package net.orion.facelinked.networks;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;
import net.orion.facelinked.config.AutoPrimaryKey;
import org.springframework.data.annotation.Id;

@Setter
@Getter
@DynamoDBTable(tableName = "networkMessages")
public class NetworkMessage {
    @Id
    private AutoPrimaryKey id;

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id != null ? id.getId() : null;
    }

    public void setId(String Id) {
        if (id == null) {
            id = new AutoPrimaryKey();
        }
        id.setId(Id);
    }

    @DynamoDBRangeKey(attributeName = "millis")
    public Long getMillis() {
        return id != null ? id.getMillis() : null;
    }

    public void setMillis(Long millis) {
        if (id == null) {
            id = new AutoPrimaryKey();
        }
        id.setMillis(millis);
    }
    @DynamoDBAttribute(attributeName = "senderId")
    @DynamoDBTypeConverted(converter = NetworkMemberConverter.class)
    private NetworkMember senderId;
    @DynamoDBAttribute(attributeName = "networkId")
    private String networkId;
    @DynamoDBAttribute(attributeName = "content")
    private String content;

    public NetworkMessage() {
    }

    public NetworkMessage(NetworkMember senderId, String networkId, String content, AutoPrimaryKey id) {
        this.senderId = senderId;
        this.networkId = networkId;
        this.content = content;
        this.id = id;
    }
}