package net.orion.facelinked.networks;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.util.List;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "networks")
public class Network {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute(attributeName = "name")
    private String name;
    @DynamoDBAttribute(attributeName = "description")
    private String description;
    @DynamoDBAttribute(attributeName = "creatorId")
    private String creatorId;
    @DynamoDBAttribute(attributeName = "isPrivate")
    private boolean isPrivate;
    @DynamoDBAttribute(attributeName = "members")
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.L)
    private List<NetworkMember> members;
    @DynamoDBAttribute(attributeName = "networkPicturePath")
    private String networkPicturePath;
    @DynamoDBAttribute(attributeName = "memberCount")
    private Integer memberCount;
    @DynamoDBAttribute(attributeName = "searchName")
    private String searchName;
}
