package net.orion.facelinked.chats;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import net.orion.facelinked.config.AutoPrimaryKey;
import org.springframework.data.annotation.Id;


@Getter
@Setter
@DynamoDBTable(tableName = "chatMessages")
public class ChatMessage
{
    @Id
    private AutoPrimaryKey id;

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id != null ? id.getId() : null;
    }

    public void setId(String Id) {
        if (id == null) {
            id = new AutoPrimaryKey();
        }
        id.setId(Id);
    }

    @DynamoDBRangeKey(attributeName = "millis")
    public Long getMillis() {
        return id != null ? id.getMillis() : null;
    }

    public void setMillis(Long millis) {
        if (id == null) {
            id = new AutoPrimaryKey();
        }
        id.setMillis(millis);
    }

    @DynamoDBAttribute(attributeName = "senderId")
    private String senderId;
    @DynamoDBAttribute(attributeName = "receiverId")
    private String receiverId;
    @DynamoDBAttribute(attributeName = "content")
    private String content;

    public ChatMessage() {
    }

    public ChatMessage(String senderId, String receiverId, String content, AutoPrimaryKey id) {
        this.senderId = senderId;
        this.receiverId = receiverId;
        this.content = content;
        this.id = id;
    }
}
